=== GritsH/Grits-EpamTraining-Gems/src/main/resources/gems1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
        targetNamespace="http://grits.by"
        elementFormDefault="qualified"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="gems" type="grit:gemsType" xmlns:grit="http://grits.by"/>
    <xsd:complexType name="visualParametersType">
        <xsd:sequence>
            <xsd:element name="color">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="RED"/>
                        <xsd:enumeration value="BLUE"/>
                        <xsd:enumeration value="PURPLE"/>
                        <xsd:enumeration value="TRANSPARENT"/>
                        <xsd:enumeration value="YELLOW"/>
                        <xsd:enumeration value="BLACK"/>
                        <xsd:enumeration value="WHITE"/>
                        <xsd:enumeration value="PINK"/>
                        <xsd:enumeration value="ORANGE"/>
                        <xsd:enumeration value="GREEN"/>
                        <xsd:enumeration value="BROWN"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="transparency">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="facesAmount">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="([4-9]|1[0-5])"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="gemType">
        <xsd:sequence>
            <xsd:element name="name">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="preciousness">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="SEMI_PRECIOUS"/>
                        <xsd:enumeration value="PRECIOUS"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="origin">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element type="grit:visualParametersType" name="visualParameters" xmlns:grit="http://grits.by"/>
            <xsd:element name="value">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:double">
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="addedAt">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
<!--                        <xsd:pattern value="[1-9][0-9]{3}\-.+?T[^\.]+?(Z|[\+\-].+)"/>-->
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="id" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="gemsType">
        <xsd:sequence>
            <xsd:element type="grit:gemType" name="gem" maxOccurs="unbounded" minOccurs="0"
                         xmlns:grit="http://grits.by"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== GritsH/Grits-EpamTraining-Gems/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems  xmlns="http://grits.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://tempuri.org gems1.xsd">
    <gem id="1">
        <name>Ruby</name>
        <preciousness>SEMI_PRECIOUS</preciousness>
        <origin>Brazil</origin>
        <visualParameters>
            <color>RED</color>
            <transparency>10</transparency>
            <facesAmount>10</facesAmount>
        </visualParameters>
        <value>200.15</value>
        <addedAt>2022-03-30 11:11:11</addedAt>
    </gem>
    <gem id="2">
        <name>Diamond</name>
        <preciousness>PRECIOUS</preciousness>
        <origin>North America</origin>
        <visualParameters>
            <color>TRANSPARENT</color>
            <transparency>3</transparency>
            <facesAmount>15</facesAmount>
        </visualParameters>
        <value>150.01</value>
        <addedAt>2022-03-30 12:11:11</addedAt>
    </gem>
    <gem id="3">
        <name>Quartz</name>
        <preciousness>PRECIOUS</preciousness>
        <origin>North Africa</origin>
        <visualParameters>
            <color>PINK</color>
            <transparency>13</transparency>
            <facesAmount>6</facesAmount>
        </visualParameters>
        <value>110.25</value>
        <addedAt>2022-03-30 11:12:11</addedAt>
    </gem>
</gems>
